FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY ["notcobase/notcobase.csproj", "notcobase/"]
RUN dotnet restore "notcobase/notcobase.csproj"

COPY . .
RUN dotnet publish "notcobase/notcobase.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
RUN mkdir -p /app/data

ENV ASPNETCORE_URLS=http://+:5284
EXPOSE 5284
ENTRYPOINT ["dotnet", "notcobase.dll"]
